version: '3'

networks:
  public:
  private:
    internal: true
    driver: bridge

services:
  api:
    build:
      context: ./src/api
      dockerfile: Dockerfile
    container_name: tutor-api
    volumes:
      - "./src/api:/src"
    networks:
      - private