version: '3'

networks:
  public:
  private:
    internal: true
    driver: bridge
  database:
    internal: true
    driver: bridge

services:
  api:
    build:
      context: ./src/api
      dockerfile: Dockerfile
    container_name: tutor-api
    depends_on:
      - database
    ports:
      - '5000:5000'
    volumes:
      - "./src/api:/src"
    networks:
      - public
      - private
      - database
  web:
    build:
      context: ./src/frontend
      dockerfile: Dockerfile
    container_name: tutor-web
    depends_on:
      - api
    ports:
      - '80:80'
    volumes:
      - "./src/frontend:/src"
    networks:
      - public
      - private
  database:
    image: mysql:8
    container_name: tutor-database
    restart: always
    env_file:
      - docker/env/database
    volumes:
      - database:/var/lib/mysql
    ports:
      - '3306:3306'
    networks:
      - public
      - database
    
volumes:
  database: